Stub out deploy script

diff --git a/bin/templates/scripts/strapkit/deploy b/bin/templates/scripts/strapkit/deploy
--- a/bin/templates/scripts/strapkit/deploy
+++ b/bin/templates/scripts/strapkit/deploy
@@ -1,3 +1,53 @@
 #!/bin/bash
 
-echo "Not implemented yet"
+# Utility to bail out of execution
+fail() {
+    echo "Error: $1"
+    exit 1
+}
+
+# Check adb available
+if ! which adb > /dev/null; then
+    fail "Missing adb. Please ensure android tools in path."
+fi
+
+# Check that multiple devices available
+devices=$(adb devices | grep -v "List" | grep -v '^$' | awk '{print $1}')
+
+if [ $(echo "$devices" | wc -l) -ne 2 ]; then
+    fail "Only one device detected. Please connect both wearable and handheld."
+fi
+
+echo
+echo "Installing onto handheld"
+
+handheld=
+wearable=
+for device in $devices; do
+    if [ -z "$handheld" ]; then
+        if adb -s "$device" install output/mobile-release.apk; then
+            handheld="$device"
+        else
+            wearable="$device"
+        fi
+    else
+        wearable="$device"
+    fi
+done
+
+# echo "handheld: $handheld"
+# echo "wearable: $wearable"
+
+if [ -z "$handheld" ]; then
+    fail "Failed to install application onto handheld"
+fi
+
+echo "Done!"
+echo
+echo "Installing onto wearable"
+
+if adb -s "$wearable" install output/wear-release.apk; then
+    echo "Done!"
+else
+    fail "Failed to install application onto wearable"
+fi
